# BASE DE DATOS H2 (temporal)
spring.datasource.url=jdbc:h2:mem:pjg360db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2 (abrir en: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVIDOR
server.port=8081

# Permite que data.sql corra DESPUÉS de que Hibernate cree las tablas
spring.datasource.sql-script-encoding=UTF-8
spring.jpa.defer-datasource-initialization=true

# JWT
jwt.secret=pjg360SecretKeyMundial2026SuperSeguraParaJWT
jwt.expiration=86400000